# -*- coding: utf-8 -*-
"""airbnb_price.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D0G7BLZoqzvHGU2CGDKCnfyGG9XYLnyC
"""

!pip install catboost
import warnings
warnings.simplefilter('ignore')

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.preprocessing import  LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score, KFold
from sklearn import metrics
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import Pipeline
from catboost import CatBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
#from xgboost import XGBRegressor
from sklearn.ensemble import RandomForestRegressor

df = pd.read_csv('/content/Airbnb_Data.csv')
df

df.info()

df['host_response_rate'].value_counts()

df.isnull().sum()

df = df.dropna()
df # every missing values are removed

"""y = {}
for j,items in enumerate(df["amenities"]):
  k = f"x{j}"
  y[k] = []
  for m in list(items.split(",")):
    y[k].append(m.replace('"',''))
y

res = {}
for k,items in y.items():
  c_list = []
  for i, item in enumerate(items):
    if i == 0 and item.startswith('{'):
            item = item[1:]  # Remove the first character '{'
        # Remove '}' from last item if present
    if i == len(items) - 1 and item.endswith('}'):
            item = item[:-1]  # Remove the last character '}'

    c_list.append(item)
  res[k] = c_list
res"

res1 = []
for k,v in res.items():
  for i in v:
    res1.append(i)
res2 = list(set(res1))
res2 = res2[1:]
res2

res2
for i in res2:
  am_name = i.replace(" ", "_").replace("/", "_")
  df[am_name] = df['amenities'].apply(lambda x: 1 if i in x else 0)
df
"""

common_amenities = [
    'wireless internet', 'air conditioning', 'kitchen', 'heating', 'tv',
    'washer', 'dryer', 'free parking on premises', 'pool', 'gym',
    'elevator', 'family/kid friendly', 'hair dryer', 'iron',
    'laptop friendly workspace', 'hot tub', 'cable tv', 'buzzer/wireless intercom'
]

for amenity in common_amenities:
    clean_name = amenity.replace(" ", "_").replace("/", "_")
    df[f'has_{clean_name}'] = df['amenities'].str.contains(amenity, case=False, na=False).astype(int)

df = df.drop(columns= ["amenities","host_since","last_review","thumbnail_url"])
df

sns.distplot(df["bathrooms"])

sns.distplot(df["review_scores_rating"])

sns.distplot(df["bedrooms"])
plt.show()

# Function to plot catplot graphs
def plot_catplot(h,v,he,a):
    sns.set(font_scale=1.5)
    sns.catplot(x=h,kind=v,data=df,height=he, aspect = a)

# Function to plot catplot graphs
def plot_piechart(h):
    sns.set(font_scale=1.5)
    fig = plt.figure(figsize=(5,5))
    ax = fig.add_axes([0,0,1,1])
    ax.axis('equal')
    langs = list(df[h].unique())
    students =list(df[h].value_counts())
    ax.pie(students, labels = langs,autopct='%1.2f%%')
    plt.show()

plt.figure(figsize = (10, 8))
sns.distplot(df["log_price"])
plt.title('Price distribution')
plt.show()

sns.boxplot(df["log_price"])

for i in df.columns:
   if df[i].dtype == "float64":
      sns.boxplot(df[i])
      plt.show()

"""q1 = df["log_price"].quantile(0.25)
q3 = df["log_price"].quantile(0.75)
iqr = q3 - q1
upper = q3 + 1.5 * iqr
lower = q1 - 1.5 * iqr
df = df[(df["log_price"] < upper) & (df["log_price"] > lower)]
df"""
#

sns.boxplot(df["log_price"])

"""q1 = df["review_scores_rating"].quantile(0.25)
q3 = df["review_scores_rating"].quantile(0.75)
iqr = q3 - q1
upper = q3 + 1.5 * iqr
lower = q1 - 1.5 * iqr
df = df[(df["review_scores_rating"] < upper) & (df["review_scores_rating"] > lower)]
df"""

sns.boxplot(df["review_scores_rating"])

"""q1 = df["beds"].quantile(0.25)
q3 = df["beds"].quantile(0.75)
iqr = q3 - q1
upper = q3 + 1.5 * iqr
lower = q1 - 1.5 * iqr
df = df[(df["beds"] < upper) & (df["beds"] > lower)]
df"""

sns.boxplot(df["beds"])

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for i in df.columns:
  if df[i].dtype == "object" or df[i].dtype == "bool":
    df[i] = le.fit_transform(df[i])
df # label encoding

plt.figure(figsize = (10,10))
sns.heatmap(df.corr()[["log_price"]], annot=True, fmt=".2f", cmap="seismic")
plt.show()

x1 = df.drop(columns=["log_price"])
x1

y = df["log_price"]
y

"""# **RANDOM FOREST REGRESSOR**

By using this algorithm, I am getting accuracy of 76%
"""

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x1,y,test_size=0.2,random_state=42)
#rf = RandomForestRegressor()

rf = RandomForestRegressor()
rf.fit(x_train,y_train)
y_pred = rf.predict(x_test)
r2_rf = metrics.r2_score(y_test, y_pred)
print(r2_rf)

"""# **CATBOOST REGRESSOR**

Catboost algorithm is giving me accuracy of 78%
"""

model_CBR = CatBoostRegressor()

model_CBR.fit(x_train, y_train)

cross_val_score(model_CBR, x_train, y_train,
                           scoring='r2',
                           cv=KFold(n_splits=5,
                                    shuffle=True,
                                    random_state=2022,
                                    ))

y_pred_cbr = model_CBR.predict(x_test)

mae_cbr  = metrics.mean_absolute_error(y_test, y_pred_cbr)
mse_cbr  = metrics.mean_squared_error(y_test, y_pred_cbr)
rmse_cbr = np.sqrt(metrics.mean_squared_error(y_test, y_pred_cbr))
r2_cbr   = metrics.r2_score(y_test, y_pred_cbr)


print('\nMean Absolute Error of CatBoost Regressor     : ', mae_cbr)
print('\nMean Squarred Error of CatBoost Regressor     : ', mse_cbr)
print('\nRoot Mean Squarred Error of CatBoost Regressor: ', rmse_cbr)
print('\nR2 Score of CatBoost Regressor                : ', r2_cbr)

"""# **GRADIENT BOOSTING REGRESSOR**

Gradient boosting Regressor is giving me accuracy of 74%
"""

gb = GradientBoostingRegressor(n_estimators=100, learning_rate=0.1, max_depth=3)

gb.fit(x_train, y_train)

y_pred_gb = gb.predict(x_test)

mae_gb  = metrics.mean_absolute_error(y_test, y_pred_gb)
mse_gb  = metrics.mean_squared_error(y_test, y_pred_gb)
rmse_gb = np.sqrt(metrics.mean_squared_error(y_test, y_pred_gb))
r2_gb   = metrics.r2_score(y_test, y_pred_gb)
print(r2_gb)

"""# **ALGORITHM ACCURACY COMPARISON**"""

accu = pd.DataFrame({
    'Model': ['Random Forest Regressor', 'CatBoost Regressor', 'Gradient Boosting Regressor'],
    'R2 Score': [r2_rf, r2_cbr, r2_gb]
})
accu

import plotly.express as px
px.bar(accu, x='Model', y='R2 Score', title='Algorithm Accuracy Comparison')
#

